### ISSUE TITLE
Minecraft crashes when binding perspective toggle to the < and > key

### ISSUE THREAD

**Issue by StoicIndividual** [DJtheRedstoner/PerspectiveModv4#10]
I have and extra key on my keyboard that can type < and >, but everytime I try binding the perspective toggle to that key it just crashes forcing me to remove the mod everytime that happens or it won't boot, here's the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_20.29.0_Forge_1.8.9.jar)
  ModTweaker (Patcher-1.4.1 (1.8.9).jar)
  FMLLoadingPlugin (Sk1er_Old_Animations-1.0_-_beta_6.jar)
  PatcherTweaker (Patcher-1.4.1 (1.8.9).jar)
  DamageTilt ASM (DamageTilt-1.8.9-0.1.0.jar)
  PerspectiveModTweaker (PerspectiveMod-4.3.jar)
  OptifinePatcherTweaker (Sk1er_Old_Animations-1.0_-_beta_6.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 12/20/20 4:17 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:544)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:252)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at me.djtheredstoner.perspectivemod.PerspectiveMod.tick(PerspectiveMod.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_43_PerspectiveMod_tick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:544)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:252)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at me.djtheredstoner.perspectivemod.PerspectiveMod.tick(PerspectiveMod.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_43_PerspectiveMod_tick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SUBSONIC7007'/175, l='MpServer', x=-45.22, y=69.00, z=-25.60]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -16.00,64.00,-4.00 - World: (-16,64,-4), Chunk: (at 0,4,12 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 13364 game time, 23436 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntitySkeleton['Skeleton'/2307, l='MpServer', x=-51.02, y=24.00, z=-97.36], EntitySkeleton['Skeleton'/2308, l='MpServer', x=-52.09, y=24.00, z=-96.38], EntitySkeleton['Skeleton'/2309, l='MpServer', x=-51.79, y=24.00, z=-97.73], EntityBat['Bat'/10, l='MpServer', x=-115.88, y=22.09, z=-81.53], EntityZombie['Zombie'/11, l='MpServer', x=-126.50, y=19.00, z=-82.09], EntityBat['Bat'/12, l='MpServer', x=-115.91, y=22.44, z=-76.88], EntityBat['Bat'/13, l='MpServer', x=-114.31, y=22.81, z=-77.66], EntityEnderman['Enderman'/16, l='MpServer', x=-108.50, y=25.00, z=-42.50], EntitySquid['Squid'/18, l='MpServer', x=-104.50, y=59.06, z=-25.44], EntityCreeper['Creeper'/21, l='MpServer', x=-95.50, y=23.00, z=-38.50], EntitySquid['Squid'/22, l='MpServer', x=-81.74, y=61.02, z=-34.59], EntityZombie['Zombie'/23, l='MpServer', x=-80.50, y=23.00, z=-26.50], EntitySquid['Squid'/24, l='MpServer', x=-72.54, y=59.09, z=-27.29], EntitySkeleton['Skeleton'/25, l='MpServer', x=-91.47, y=18.00, z=6.13], EntityCreeper['Creeper'/27, l='MpServer', x=-63.83, y=64.00, z=-57.66], EntityCreeper['Creeper'/28, l='MpServer', x=-79.27, y=47.00, z=-33.68], EntityZombie['Zombie'/30, l='MpServer', x=-79.72, y=47.00, z=-32.88], EntityCreeper['Creeper'/32, l='MpServer', x=-71.50, y=23.00, z=-25.50], EntityCreeper['Creeper'/33, l='MpServer', x=-64.34, y=64.15, z=-28.32], EntityCreeper['Creeper'/34, l='MpServer', x=-58.50, y=20.00, z=-104.50], EntityBat['Bat'/2339, l='MpServer', x=-28.17, y=14.04, z=-32.46], EntitySkeleton['Skeleton'/36, l='MpServer', x=-42.28, y=63.17, z=-73.53], EntityBat['Bat'/2340, l='MpServer', x=-21.23, y=14.00, z=-36.39], EntityZombie['Zombie'/37, l='MpServer', x=-53.01, y=73.07, z=-54.56], EntityCreeper['Creeper'/38, l='MpServer', x=-64.63, y=73.00, z=-42.22], EntitySkeleton['Skeleton'/39, l='MpServer', x=-61.49, y=70.76, z=-31.72], EntityCreeper['Creeper'/40, l='MpServer', x=-61.56, y=69.91, z=-30.76], EntityBat['Bat'/41, l='MpServer', x=-44.56, y=25.39, z=-8.51], EntitySkeleton['Skeleton'/42, l='MpServer', x=-53.50, y=62.49, z=-10.02], EntityZombie['Zombie'/43, l='MpServer', x=-51.59, y=48.00, z=-12.97], EntitySquid['Squid'/44, l='MpServer', x=-55.94, y=45.44, z=-1.53], EntitySquid['Squid'/45, l='MpServer', x=-54.09, y=55.81, z=20.34], EntityZombie['Zombie'/48, l='MpServer', x=-41.66, y=11.00, z=-73.94], EntityZombie['Zombie'/49, l='MpServer', x=-45.41, y=11.00, z=-77.13], EntityCreeper['Creeper'/50, l='MpServer', x=-46.31, y=11.00, z=-77.97], EntityZombie['Zombie'/51, l='MpServer', x=-45.63, y=71.00, z=-42.03], EntitySpider['Spider'/52, l='MpServer', x=-38.81, y=70.00, z=-57.63], EntityCreeper['Creeper'/53, l='MpServer', x=-27.41, y=68.00, z=-31.00], EntityCreeper['Creeper'/54, l='MpServer', x=-37.76, y=70.00, z=-52.11], EntityCreeper['Creeper'/55, l='MpServer', x=-41.69, y=38.00, z=-19.34], EntityCreeper['Creeper'/56, l='MpServer', x=-50.50, y=41.00, z=-26.13], EntityCreeper['Creeper'/57, l='MpServer', x=-29.94, y=69.00, z=-31.34], EntityZombie['Zombie'/58, l='MpServer', x=-43.94, y=68.00, z=-21.56], EntityCreeper['Creeper'/59, l='MpServer', x=-45.50, y=68.00, z=-22.03], EntityCreeper['Creeper'/60, l='MpServer', x=-51.06, y=38.00, z=-8.59], EntitySkeleton['Skeleton'/70, l='MpServer', x=-16.13, y=30.00, z=-89.53], EntityZombie['Zombie'/71, l='MpServer', x=-25.22, y=67.00, z=-65.66], EntitySpider['Spider'/72, l='MpServer', x=-13.00, y=67.91, z=-49.50], EntityZombie['Zombie'/73, l='MpServer', x=-32.19, y=70.00, z=-58.63], EntityWitch['Witch'/75, l='MpServer', x=-34.34, y=70.00, z=-49.19], EntityEnderman['Enderman'/76, l='MpServer', x=-28.72, y=42.00, z=-23.47], EntityEnderman['Enderman'/77, l='MpServer', x=-28.50, y=41.00, z=-27.50], EntityPig['Pig'/78, l='MpServer', x=-18.69, y=66.00, z=4.94], EntitySkeleton['Skeleton'/79, l='MpServer', x=-17.53, y=28.00, z=5.34], EntityBat['Bat'/80, l='MpServer', x=-19.49, y=39.03, z=7.45], EntitySkeleton['Skeleton'/86, l='MpServer', x=-15.31, y=30.00, z=-89.50], EntityZombie['Zombie'/89, l='MpServer', x=-11.72, y=29.00, z=-77.53], EntityZombie['Zombie'/92, l='MpServer', x=-4.53, y=34.00, z=-76.84], EntityBat['Bat'/93, l='MpServer', x=-11.97, y=33.20, z=-62.18], EntitySpider['Spider'/94, l='MpServer', x=-5.72, y=33.09, z=-62.72], EntityBat['Bat'/95, l='MpServer', x=7.88, y=37.00, z=-43.20], EntityPig['Pig'/97, l='MpServer', x=-10.09, y=68.00, z=-23.09], EntitySkeleton['Skeleton'/2145, l='MpServer', x=-80.50, y=29.00, z=-9.50], EntityCreeper['Creeper'/98, l='MpServer', x=-15.25, y=67.00, z=-12.13], EntityBat['Bat'/100, l='MpServer', x=-9.69, y=36.03, z=18.66], EntityChicken['Chicken'/103, l='MpServer', x=8.19, y=62.56, z=-53.63], EntitySkeleton['Skeleton'/104, l='MpServer', x=4.38, y=63.00, z=-57.47], EntityChicken['Chicken'/105, l='MpServer', x=6.94, y=62.66, z=-58.53], EntitySkeleton['Skeleton'/2154, l='MpServer', x=-82.69, y=29.00, z=-12.34], EntityItem['item.item.sulphur'/106, l='MpServer', x=12.19, y=19.00, z=-35.06], EntitySpider['Spider'/107, l='MpServer', x=7.66, y=22.00, z=-39.88], EntitySkeleton['Skeleton'/2155, l='MpServer', x=-76.50, y=26.00, z=33.50], EntitySpider['Spider'/108, l='MpServer', x=6.50, y=23.00, z=-34.84], EntityZombie['Zombie'/2156, l='MpServer', x=-83.47, y=29.00, z=-16.06], EntityCreeper['Creeper'/110, l='MpServer', x=6.50, y=23.00, z=-33.03], EntitySpider['Spider'/111, l='MpServer', x=7.72, y=64.00, z=-23.34], EntityZombie['Zombie'/112, l='MpServer', x=19.09, y=64.00, z=-33.66], EntityZombie['Zombie'/113, l='MpServer', x=7.34, y=24.00, z=-29.66], EntityBat['Bat'/114, l='MpServer', x=15.25, y=34.10, z=-20.25], EntityChicken['Chicken'/115, l='MpServer', x=13.50, y=62.63, z=-19.66], EntityChicken['Chicken'/116, l='MpServer', x=14.25, y=62.50, z=-22.59], EntityItem['item.item.egg'/117, l='MpServer', x=14.72, y=53.00, z=-18.13], EntitySpider['Spider'/118, l='MpServer', x=15.78, y=63.97, z=-26.72], EntityChicken['Chicken'/120, l='MpServer', x=19.44, y=63.00, z=-26.66], EntitySpider['Spider'/121, l='MpServer', x=-4.03, y=67.00, z=-37.66], EntityCreeper['Creeper'/122, l='MpServer', x=0.09, y=62.34, z=-3.53], EntitySquid['Squid'/123, l='MpServer', x=11.72, y=50.41, z=14.34], EntitySquid['Squid'/124, l='MpServer', x=6.59, y=49.75, z=18.09], EntityChicken['Chicken'/128, l='MpServer', x=30.50, y=62.53, z=-50.44], EntityChicken['Chicken'/129, l='MpServer', x=22.72, y=62.59, z=-49.16], EntityChicken['Chicken'/130, l='MpServer', x=30.81, y=62.63, z=-47.59], EntityChicken['Chicken'/131, l='MpServer', x=12.63, y=64.00, z=-38.44], EntityChicken['Chicken'/132, l='MpServer', x=27.31, y=64.00, z=-33.59], EntityZombie['Zombie'/133, l='MpServer', x=28.09, y=63.00, z=-30.47], EntityZombie['Zombie'/134, l='MpServer', x=11.94, y=63.00, z=-46.47], EntityBat['Bat'/135, l='MpServer', x=30.13, y=28.00, z=-20.53], EntityPig['Pig'/136, l='MpServer', x=20.06, y=63.00, z=-23.97], EntityChicken['Chicken'/137, l='MpServer', x=18.13, y=62.56, z=-21.97], EntityBat['Bat'/2195, l='MpServer', x=-84.53, y=13.94, z=-40.03], EntityZombie['Zombie'/2221, l='MpServer', x=-116.13, y=27.00, z=-69.53], EntityZombie['Zombie'/2222, l='MpServer', x=-104.50, y=26.00, z=-76.50], EntityPlayerSP['SUBSONIC7007'/175, l='MpServer', x=-45.22, y=69.00, z=-25.60], EntityBat['Bat'/2250, l='MpServer', x=-22.08, y=14.10, z=-34.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.4.0-58-generic
	Java Version: 1.8.0_275, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 357120288 bytes (340 MB) / 771751936 bytes (736 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	xaerominimap_core{1.8.9-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCHIJAAAA	redperautosprintmod{2.0.0} [AutoSprint] (AutoSprint-Forge-1.8-1.12-2.0.0.jar) 
	UCHIJAAAA	blockoverlay{3.2} [Block Overlay] (Block_Overlay_3.2.jar) 
	UCHIJAAAA	damagetilt{0.1.0} [Damage Tilt] (DamageTilt-1.8.9-0.1.0.jar) 
	UCHIJAAAA	patcher{1.4.1} [Patcher] (Patcher-1.4.1 (1.8.9).jar) 
	UCHIJAAAA	djperspectivemod{4.3} [Perspective Mod v4] (PerspectiveMod-4.3.jar) 
	UCHIJAAAA	sk1er_old_animations{1.0} [Sk1er Old Animations] (Sk1er_Old_Animations-1.0_-_beta_6.jar) 
	UCHIJAAAA	ChatToggle{1.0} [ChatToggle] (ToggleChat-1.8.9.jar) 
	UCHIJAAAA	XaeroMinimap{20.29.0} [Xaero's Minimap] (Xaeros_Minimap_20.29.0_Forge_1.8.9.jar) 
	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_20.29.0_Forge_1.8.9.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
ModTweaker (Patcher-1.4.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
FMLLoadingPlugin (Sk1er_Old_Animations-1.0_-_beta_6.jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.mods.sk1eroldanimations.tweaker.ClassTransformer
PatcherTweaker (Patcher-1.4.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
DamageTilt ASM (DamageTilt-1.8.9-0.1.0.jar)
  com.charles445.damagetilt.asm.DamageTiltASM
PerspectiveModTweaker (PerspectiveMod-4.3.jar)
  me.djtheredstoner.perspectivemod.asm.ClassTransformer
OptifinePatcherTweaker (Sk1er_Old_Animations-1.0_-_beta_6.jar)
  club.sk1er.mods.sk1eroldanimations.tweaker.OptifineClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 450.80.02' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.80.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Combat+ Regular Modified.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 450.80.02
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by DJtheRedstoner** [comment]
Most likely an LWJGL issue, probably not to much I can do about it, please join my discord server (link in readme) so I can debug it further.

**Comment by proudmuslim-dev** [comment]
hastebin: exists
